### ISSUE TITLE
запись в txt

### ISSUE THREAD

**Issue by Arkveles** [evgenyunholy/UnholyMegaBrut#2]

**Comment by Arkveles** [comment]
Добрый день. Можете мне помочь... Я пытаюсь настроить программу (EthMnemoBrut.py) , для дополнительной записи сгенерированных фраз и кошельков в текстовый файл. Смог только добиться запись при запуске ( 2 - Print all(slow) ) но хочется побольше скорости, а (1 - Print only count(fast) ) категорически отказывается записываться) кучу всего перепробовал но тщетно.
![Снимок экрана 2023-01-05 001419](https://user-images.githubusercontent.com/42773942/210651182-95ff2996-e692-4daa-996e-0c0d91e86f3a.png)

**Comment by Mizogg** [comment]
Hi Arkveles,

maybe just create a 3rd option to save all results when scanning. I don't use sys.stdout I would just add 
with open("log.txt", "a") as f:
              f.write(output)
If you add this to another Option they have to choice then to save all results.

**Comment by Arkveles** [comment]
Thanks.
